name: Test with Maven

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - 'releases/**'
  pull_request:
    branches:
      - 'develop'
      - 'main'
      - 'releases/**'

jobs:
  maven-tests:
    uses: wultra/wultra-infrastructure/.github/workflows/maven-test.yml@develop
    secrets: inherit
    with:
      java_version: 21